services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clubhub
      POSTGRES_USER: clubhub
      POSTGRES_PASSWORD: clubhub
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  backend:
    build: .
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/clubhub
      QUARKUS_DATASOURCE_USERNAME: clubhub
      QUARKUS_DATASOURCE_PASSWORD: clubhub
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8081:8080"

volumes:
  keycloak_data:
