services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clubhub
      POSTGRES_USER: clubhub
      POSTGRES_PASSWORD: clubhub
    ports:
      - "5432:5432"

  backend:
    build: .
    env_file:
      - .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/clubhub
      QUARKUS_DATASOURCE_USERNAME: clubhub
      QUARKUS_DATASOURCE_PASSWORD: clubhub
    depends_on:
      - postgres
    ports:
      - "8080:8080"

