services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clubhub
      POSTGRES_USER: clubhub
      POSTGRES_PASSWORD: clubhub
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U clubhub" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/clubhub
      QUARKUS_DATASOURCE_USERNAME: clubhub
      QUARKUS_DATASOURCE_PASSWORD: clubhub
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  pgdata:
