package com.clubhub.entity;

public enum Subject {
	COMPUTER_SCIENCE,
	MATHEMATICS,
	PHYSICS,
	ENGINEERING,
	BUSINESS,
	LAW,
	MEDICINE,
	ARCHITECTURE,
	CIVIL_ENGINEERING,
	ELECTRICAL_ENGINEERING,
	MECHANICAL_ENGINEERING,
	MEDIA_DESIGN,
	SOCIAL_WORK,
	BUSINESS_ADMINISTRATION,
	INDUSTRIAL_ENGINEERING
}
